.TH AWLSIM-TEST "1" "2016" "awlsim-test" "User Commands"
.SH NAME
awlsim-test \- Step 7 compatible AWL/STL Soft\-PLC written in Python
.SH SYNOPSIS
.B awlsim-test
[\fIOPTIONS\fR]
.SH DESCRIPTION
Step 7 compatible AWL/STL Soft\-PLC testing interface.
.SH OPTIONS
.TP
\fB\-h\fR|\-\-help
Print help information
.SH AUTHORS
Michael Buesch
