.TH AWLSIM-LINUXCNC-HAL "1" "2016" "awlsim-linuxcnc-hal" "User Commands"
.SH NAME
awlsim-linuxcnc-hal \- Step 7 compatible AWL/STL Soft\-PLC written in Python
.SH SYNOPSIS
.B awlsim-linuxcnc-hal
[\fIOPTIONS\fR]
.SH DESCRIPTION
Step 7 compatible AWL/STL Soft\-PLC linuxcnc-hal.
.SH OPTIONS
.TP
\fB\-h\fR|\-\-help
Print help information
.SH AUTHORS
Michael Buesch
