.TH AWLSIM-PROUPGRADE "1" "2016" "awlsim-proupgrade" "User Commands"
.SH NAME
awlsim-proupgrade \- Step 7 compatible AWL/STL Soft\-PLC written in Python
.SH SYNOPSIS
.B awlsim-proupgrade
[\fIOPTIONS\fR]
.SH DESCRIPTION
Awlsim project file format upgrade utility.
.SH OPTIONS
.TP
\fB\-h\fR|\-\-help
Print help information
.SH AUTHORS
Michael Buesch
