.TH AWLSIM-CLIENT "1" "2016" "awlsim-client" "User Commands"
.SH NAME
awlsim-client \- Step 7 compatible AWL/STL Soft\-PLC written in Python
.SH SYNOPSIS
.B awlsim-client
[\fIOPTIONS\fR]
.SH DESCRIPTION
Step 7 compatible AWL/STL Soft\-PLC client interface.
.SH OPTIONS
.TP
\fB\-h\fR|\-\-help
Print help information
.SH AUTHORS
Michael Buesch
