.TH PILC-HAT-CONF "1" "2016" "pilc-hat-conf" "User Commands"
.SH NAME
pilc-hat-conf \- Raspberry Pi PiLC HAT configuration tool
.SH SYNOPSIS
.B pilc-hat-conf
[\fIOPTIONS\fR]
.SH DESCRIPTION
Configuration tool for the PiLC HAT.
.SH OPTIONS
.TP
\fB\-h\fR|\-\-help
Print help information
.SH AUTHORS
Michael Buesch
