.TH AWLSIM-SYMTAB "1" "2016" "awlsim-symtab" "User Commands"
.SH NAME
awlsim-symtab \- Step 7 compatible AWL/STL Soft\-PLC written in Python
.SH SYNOPSIS
.B awlsim-symtab
[\fIOPTIONS\fR]
.SH DESCRIPTION
Step 7 compatible AWL/STL Soft\-PLC symbol table parser.
.SH OPTIONS
.TP
\fB\-h\fR|\-\-help
Print help information
.SH AUTHORS
Michael Buesch
