.TH AWLSIM-SERVER "1" "2016" "awlsim-server" "User Commands"
.SH NAME
awlsim-server \- Step 7 compatible AWL/STL Soft\-PLC written in Python
.SH SYNOPSIS
.B awlsim-server
[\fIOPTIONS\fR]
.SH DESCRIPTION
Step 7 compatible AWL/STL Soft\-PLC core server.
.SH OPTIONS
.TP
\fB\-h\fR|\-\-help
Print help information
.SH AUTHORS
Michael Buesch
