# AUTOMATICALLY GENERATED FILE
# DO NOT EDIT

# Generated from document-close-4.svg

icon_doc_close = b'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAA'\
                 b'BHNCSVQICAgIfAhkiAAAAAlwSFlzAAAOxAAADsQBlSsOGwAA'\
                 b'ChFJREFUaIHtmmtwVOUZx3/n7C2bZHOBJCQhBLmJqAhmhmI7'\
                 b'YgtoClOtbfEyMF5AsfFSL3zqgLV1rEUc7agzVVpThAKWTscK'\
                 b'Xqh4r8goio4oWCSQbEjIhU2y2fvlnLPn7Yezu9ls9pIEpvVD'\
                 b'n5l33rPn8p7f/3mf5znvObMS/wNbC4skuEuGi20wwQwOE9gl'\
                 b'MAMI0GIQ1sAXAXcMnBJs/jO8mT6W9N8Evw0cEjxkgWV2qLND'\
                 b'eTVQW1FB7dy5FE6ahAACvb10ffUVp91u+oEIuENwWsA7MXj4'\
                 b'BfDnE7AcqDmX8BVQ+gO4aSLUl8HEGSBdfNFFTL7pJornzQMp'\
                 b'DUUI/J9/TseOHXzZ0kIn6CFoj8DnNrjrWRjIJWC1rutbFVUF'\
                 b'YZw14sT4DXNOYfycoNvNzjvuwPXZZ0jd3TRIErNuvJEJy5cj'\
                 b'pYOnmRCC/j17OL57N18CHuiMwIFBuP0lCJuzXaioKv39A0iS'\
                 b'FG8kb5bYl9ge1qeKkySErrNn/Xpchw8jdXdzGTD1hhtwLFiA'\
                 b'NtiPJBk+QgehZ2YpvfxyZus69lde4SBMccPCMlgP/DqrAABZ'\
                 b'loAh+JwC0sAT+77et4+OgwdROztZCFTOn4995jS08BlihcWI'\
                 b'gBeb1ZIUILShFo5GkUtKMIfDFM6ZQ0VLCw3HjvExTFXh2rXw'\
                 b'TzkbfAJhaAaGtxHeTz0e36fHYny6bRtqVxf1QlBusVA8/2KU'\
                 b'aDeDksZ5Teso/v6VuFxt6GofQu0DtQ9d6eNMbyvlV/+IGevW'\
                 b'0R8KEezupnj+fMpkmWlgKoLJwN1ZBQx5mqwiRrQ0Ma0HDuDv'\
                 b'6kJ4vcwAbLW1CIuHdq+Pufc/jLmwmJorljHhhzfQdqoF9D50'\
                 b'zUVbRwvVK2+mdslSrKWlXPrII7S4XGiBALaaGmYABTBRhnmj'\
                 b'EJDd61Janz4LJ/fvR3O7qQSsgKkYTNIAga5vcH74VvI+0xtX'\
                 b'UP3TO/ni2HEOf9NC/S33Ma3xmuTxln2v037sKGp/P0gSFqDK'\
                 b'EDEhRw5kiX1jI2sOpPY9R46g+XxUxEcUkVNovV7mTi7nkyfu'\
                 b'IaoqzL1mJQAXXr2KqKJgstiYvfy6JMWhF1/gi8fWs7immKjz'\
                 b'30R7vQBUAB1Qml3AaBI3DTi1V0MhggMDiEiEkviQ5jLQFQ+6'\
                 b'38t3Z5rZt2kNEUVjwYqbAbj0Z6uHIRzY3sxnm37B4iqBOuAC'\
                 b'GeQC0CPgAGSwZxWQGh7pHs8GndpHAwFMQmDSdQriA8o2kGSQ'\
                 b'TQKTWeXaRbDjd6uJRAWLVt0y7P7vbW3moyeauL5BEPPGK1O8'\
                 b'SikRIyStYMpZRlPhR0DmEWCSZYri4yQSTcQAAUIkPAQ68d8Z'\
                 b'zGwFswPQwayBUEFEQHEZlxcRXzxlMEEm0DHMgr2sjCJZRpdl'\
                 b'YrqORUAsBLrD8KKmwOv/kmncsJXvXHfLCIAla+6gwCZ48w93'\
                 b'ctUcgTlqhI5qMY5rgA30vFUoVcgI+BzNbLNRNXkyBWYzkfgN'\
                 b'w4OgRkAJwfuHZRb9cjj84dea+frN7cnf31v1cy5bt5mPTkpo'\
                 b'FhBW0KLGWFFDgJojiTMnb74QSj23rqEB9wcfoCoKKhBzg1wJ'\
                 b'xz0yl/92Kxf+ZAj+mzea6XmtCWQJmwVmLjGONVzfhNUk+PqZ'\
                 b'uzm/SBAaxBjLEBDO/xxI384AL2WAB6hdvBhHaSkmjJtGQ+B3'\
                 b'QcHE6cxc+uPkfVrfaOb035uYO00wb6ZO1z/W0LF/aCZmLb0O'\
                 b'84Q6Am4IeY2xTEABeHIuJTICZ/J4ljCasHAhVbNnYy0ogLiI'\
                 b'0BlwdJzkvduvQvV7cL7eTHtzEzWFgvAAhN1QV67T9dc19Hy4'\
                 b'HcXfz6FfLaVa7cR91BhDAswQLobWbGvZW1VV3RYIBkcHn8H7'\
                 b'id737rscvu02zGfOMCAEGiBboKAO7LOnEws4KSkVmIvAXAAm'\
                 b'a9y9QCQiY3JMRTnt5Mx+iLqN8lkGIgQ9JXB7/jKaCjwK+HQB'\
                 b'pVdeSeWSJYT27qXW66UDiKqgdIASaqOgAvwKWIJgshsCZJOR'\
                 b'gkLo+Fud9H0BWtCArwGi4LHAu1fAvpwzEAyFRq518m2n9AmL'\
                 b'eb0cW7YMU0sLut/PCSAQPyZbwVYK1nKwOYzZIQaKH4Iuw+sA'\
                 b'xcAsQAefH47VQuP54Ms7A8PW+eOAlyQJc1kZM3bt4tSKFRR1'\
                 b'dtLg9dIlBE4gqkC0D+jLzGABzgPqjOegZwDa/LDifPDB0EMy'\
                 b'i4KRsMOEpG9ngE9Y4bRp1L/6KpFLLsFWWcmsggIagQXAFKAE'\
                 b'46lqxnjC1gDzgUbgArsdHfyn4OO9sPwa6Ep1cia7VdW0beF4'\
                 b'CKUmcLrXM8GnC0ndp6kqRzdupGTXLop8PuRwGBQFSVVBj79T'\
                 b'yjLCYgGrFb2wkIGqKh4/cuRvL8LNGM+xoXFzCgiHh4OmgY8G'\
                 b'PpuY/t5eTm7ZAu+/T0VXF8WBQPK4LkkMlpfTP3UqpsZGLly1'\
                 b'isrKyjXAthFjZROgJQTkAc8FnGsmkrC6Tk9PD/3d3UT7+0GW'\
                 b'sVVVUVVdTXV1NbJsRLksyxkF5EziTMmbCjIW+GxiTCYTdXV1'\
                 b'1NXV5cDI5uc8ApIVKE1IPs/mg88FNFbLPQOMLKWZIM4VvMj2'\
                 b'YpDDRhVCkNv72S/PDy+ESLbE7xHXnKsQygQy3plIBRdCEIvF'\
                 b'0HV9mJikw3K8OI46hM4mbjPBJ2A1TUPTtKSARAOQZdmoQmbb'\
                 b'+AWkg4zV+9ngY7EYqqomWzgcQVGiqJqGHosLMMnY7EW0dRxt'\
                 b'BQbHLiBP/I3VEvCapqGqKoqiEAyFCAQCRMIRItEIqqISi8/A'\
                 b'xKpJDLpcvnvWrn0G2DsWAQJyh894vJ/qeUVR8Hp9eL1e/H4/'\
                 b'wVCISDiCpmuUOBxMnzETr8cdW3ff3Y+dOHFiM2lLiHwCMgKf'\
                 b'TR4kYj4RMl6vD4/Hw+nTnQSDYeyFdiZVV1E/ZQpFRUW0tbWJ'\
                 b'DRs2PH7ok0NPZoMfk4DRWDbvJypLImFDoRB+vx+Px0MgEGDl'\
                 b'ypXxSqQRCARxtjt5dNPG595+6+3f5IKHXMvpUXp7NLOSWio1'\
                 b'TSMYDBIIBPD7A1ht9mHw7e1Onn7mqZ17Xnr5gXzwuQWcY0vE'\
                 b'fyQSJRyOEAqHCYaCTJpUOQz+2T8+t3vHX3auZhTwMJoXmoy7'\
                 b'x5YLieqj6zqKohBVoihRBVXTmFpfn4R/7k+bX97y/JbrMT77'\
                 b'jMpyftyN044J1rhkePwneiMPVDRVQ1EVShzFOBwOnO1Onnr6'\
                 b'qR07t+9cMxb4nAIg+8vCeCx12aALoyJdMGcOrW2tYuOmjc/u'\
                 b'fmn3A4wRHs5xFRqLVVRPJhDwxx586MHH3tn31sOMAx7yCEh8'\
                 b'BT8bS397M5lM2IpKCIdDvnvvvf/RTw9++nuMr+zjsqwCZFnG'\
                 b'ZrVmhBmNJc4VQiAkCSGbwGzFUlyGy9nVuu7epidPHj/+PGcB'\
                 b'D9kdfBXn+K8GadaH8ceNs4L/v30b7D9FKIWoKkHGBQAAAABJ'\
                 b'RU5ErkJggg=='
