# AUTOMATICALLY GENERATED FILE
# DO NOT EDIT

# Generated from stdlib-package.png

icon_stdlib = b'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAA'\
              b'BHNCSVQICAgIfAhkiAAAAAlwSFlzAAAN1wAADdcBQiibeAAA'\
              b'CcxJREFUaIHtmmtsHcUVx39nZvfuvde+fsWOnacdnDgJEDUh'\
              b'QYQ2IeTBI6S0pS00kJKqVP1UKqqqUqUKqaJfqlalQAFV6ifU'\
              b'wieKhFTEIy0Jj1YttDwDpEnzTgiNE8d24vhx7+6cfti96+sk'\
              b'foSYIKSOtPLMzu7M/3fmzJmZuxZV5bOczKct4ELT/wEmmh77'\
              b'tmQ/iXYvGkBtfe1Hf/heTe+D3/LXTWa7Fw2gKiN1N3330ZoZ'\
              b'LW3PPHxn9v4nbxM7Ge1eNIDANwSFKVx/58+CxStuvruzuuof'\
              b'j9wu0y+03YsGoOrAOYpH3+KyJasyN2269wrJFXY8uNFbfyHt'\
              b'ymStA49sljlhaNcG2fyXPc9eE/i6Y/OjPcvL9dvurddlmx9j'\
              b'YP9LuKiIBDW4oImtT/12oKfrw98ePzjw459u0/B8+/U+ruD7'\
              b'75BGT+xqm8ldZ62/tq554fSFy28xM+YtzeTrZ/D8rzcsGfGC'\
              b'okShIAICUf9xXP8J1mzYmNu145273zPbbnxks3zx7t/rvk8E'\
              b'4Hdfknx/wfu8MXa952VuLlQ3t3ZcsTZqW7QqW988R4wxuNIA'\
              b'rjSANRbvLOcUnDoQEDEgBsIixd79tM1qykxt2bRg67NPvPvQ'\
              b'puCue54YenJSAR7eKO22qfDGJe1L7bxFK/JTprebTDaHugh1'\
              b'JcKTB1EFjAWxKIolyjxwu1Vig7OorYC6EBBETHIJghIN9ZFx'\
              b'kbl+/S3Vf33phcce+qY3cM/j4TOTBmBy+Z9cu+GuQsuMNqOq'\
              b'aPEEpZJBjA/ly3ogHhhDqRRR3zSTm275EVW5gKp8wL+f/iFo'\
              b'hDE+zoWICFSAoBEMdrHsyuX5V1/e+n1gQgDjRqH77hOjql9r'\
              b'bJlpomIfLhpCkQrhmfgy8V8xAS4KITxFf9c+hroPUOo5QHXT'\
              b'XA7983GkeiY2NwUxNnUlEUnzgQlxUWnlfRNcuccFqN3JVXUN'\
              b'06wVYr81PhgvsX4mBRGbQWwGbIBGSTAJByDqh7CflvmryVU3'\
              b'snPLL+k+ug9baI3fGTESBtWImbNaXe2AXT0RgHFdyIj/9cuX'\
              b'XJ1TjWIXkbJ4D2wiPgWJ77nSIBoVKR57l75ejzDwkaS9KbM/'\
              b'R++hNzi26yWmdKyluroOFx0fMRKzZrfmDx8+eCvw3AUDWM/b'\
              b'OHV6m1XVRKwXCzX+MIyXwXhViJ/DeDmK3R8iXp7ctGUUqrLU'\
              b'VGdjSyepCTjZdZj/vv88JwuzaZh5KdYdRaWEiKEq6wvqvoLI'\
              b'dxhnoRoT4DebZF6uqq4uE+RQDIhNrJxBvDzi5xE/R3/fKXr3'\
              b'v07f0R1EvXtxJ/ehQQvhqQ8JowxhFFChP+5YI2pmr6Cncy8H'\
              b'tm8laOxgal0BiboRHaKuvj7z4DeOLvkBvPmxARTv1ssXL/cV'\
              b'A9ZH/BzF0KO3+wTdx9+nr+sAxa6d2KibyBmGqEIzDWSrllGo'\
              b'ziZtnN2qIEnYBameQYl6+o4d5UhnQNOUOlqqIubOnZ890d31'\
              b'VS4EwPczd0ydNsvv7DzG7kNdnOg+RXGgG1+KCBGqlhJ1lHQq'\
              b'IhbrWWr9HLkgj2RymCCHl89jq7JxlEFiJFU8v4R1A9hSP6bo'\
              b'Uwp8+k/1smN/D2buNJqbCtYz/m3AvR8boFQaWpDzwSv1sLg1'\
              b'g86ZivFmY71sHIG8LMbPY7wgzntZjJfD+AHGZjF+gPWyiPXj'\
              b'RU8jNBzEhUN44SDZ0gANpQFcqZ9o6DRR8TSu2A9aJMhVUyr9'\
              b'sX0sfeMCqKpVF2KNolpEI8W4AdyQggiCEIkQIYixaBIKEYNi'\
              b'UqtrYvi4TQfq4rnpIlRDNIpAQzQqoRqCwmBxCqo6bpgfNwop'\
              b'oE5Rdag6oqTzVAgai1HSUBkLTnw9UR4/M/yecwpEOOdQF+Ki'\
              b'CFxI5EJUhaDGjSdtYgAgqXiSvymAO6NckU/LrrJ8Rl257M6o'\
              b'K4fqSQEQgxJVCDpT8DkA3Bh1ZZHuHLBJWdB41Z8MAFVBnVZY'\
              b'+2xrxv7sRpbPBXAW/DkM4RwikwiAmDPEli2oYwOV826MurPg'\
              b'h5+TyQOwKC4Ogefhz1u2vQrA2muu4sVXXgNg9ReuGH7XOV5+'\
              b'bTsAK5ctGAGk6dQfP42PKSa2tnNnCI7S8nNbXozr02ci1q26'\
              b'GojD5poVy+K8i33/nR17UHWsvHJh+syIueEcwzFt7DSxSTye'\
              b'P0MCNNL3gdQ9ykJRx6KO1mHBCVjlyMbtT+x8P0GAWOiu/+xm'\
              b'3779hGEJgBvWreaFv2wDYMvWV1m6+DKKxRIf7NzDtObGVHQl'\
              b'wCuvvQfAiqXz0/t7DnXSeaKPubMaaKjJxguciyYEMK4LCSaN'\
              b'Dnv37GX+vHZuvG4NN6y7FtWI69esBGDdqqupqymwe99BLl/Y'\
              b'TmNDzVkAOMfKZQvS+yT3G2pzdLQ2cuBIT+qKLixOCGD8ETDJ'\
              b'JMaxaNFl7N69lwMHD9PRcQmN9bUjtpsiMDg4RF1tIY7lkESx'\
              b'cr2JV2lAjKFcqK3OEzllKOyMj5rGAJO0Eov14+OeGqY1N9PS'\
              b'PJWjncfYvv191l67AnWKNZbe0wO89fZ7ZIOA3t5+jGgqWowk'\
              b'tvBSqxtjY38HTg2WcKGS9X2M58cQE5I/BoCIZB643YDxUECM'\
              b'8OxzfwbA9zza2lpBBBVlxvQW/vXmu7TNnEGhpprtO3YxrbkJ'\
              b'gG1/eyNtc9vf307zr7z+QZrv6j5N5/Fe5s2ZjjE+Yv0ROlR1'\
              b'VH8aawRyAMb4GLE4MWxYf2McoZ1CsokzxnDpwvlcuqAjieGO'\
              b'luYmcMrC+e2g4FAkjUwaGz6NaoqosqDd4cpl42GMVOo4PwAR'\
              b'8YAAQKwXuwESb5dVUaOIAuLiI0oiDKfppBerqFpUFQ8X5ynv'\
              b'SJXYxxVVSdwqBlEccfcpQCAinuq5fzcdbQQ8IAOARokfx1sK'\
              b'THnrrPEkVBBc7GY2tm5cBxADSnl1La8NKURyJWVN6sRYrE0D'\
              b'ZCbRc14ABrBxe1Hye6YgEp9lRcqhJxZWhhs+tzhQobwpKD9u'\
              b'ymKTN2NXTIAqwpkxFjO8nbaMEe7HD6POpe4znMoRhjRcDls9'\
              b'7lPKIkkGrgycjJAAasujM7JlEamcA2Om0QAcEAGq4ZCI52OE'\
              b'1JplcZJYmbIbi2Kp4JBKqPKBvrITTc5skhpBVTFll42fjhhj'\
              b'URgNIASKxguODPbsnxHUziS2oUujRjwhy1sETTuXCjdJ+1Xi'\
              b'YRAXzxkRnHN4KaAOu1EykUv9p7A2+AgGiozi/6MCqGooIkNH'\
              b'joe/+NPTT/1KNcqM1sAnlURs8Ug3PweGRotAMMYnJhHJADVA'\
              b'HvCZ6P52cpICJaAfODnWQjbmNzIRyQJZPj2AQVUdHOvBcT/y'\
              b'iYjlAr6lXUAKVXXcPfWkfaX8tNJn/p89/gf/IS6GlkdtNwAA'\
              b'AABJRU5ErkJggg=='
